apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "service-mesh-gateway.gatewayName" . }}
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    app: {{ .Values.ingressGatewayName }} # use istio default controller
  servers:
  {{- range $host, $value := $.Values.rules }}
  - port:
      number: {{ $value.gateway.port }}
      name: {{ $value.gateway.name }}
      protocol:  {{ $value.gateway.protocol }}
    {{- if $value.gateway.credentialName }}
    tls:
      mode: SIMPLE
      credentialName:  {{ $value.gateway.credentialName }}
    {{- end }}
    hosts:
    # - "*"
    - "{{ $host }}"
  {{- end -}}
