service-mesh-app:
  # -- workload(App) 이름
  fullnameOverride: "nginx"
  # -- 차트 이름(없을 경우 Chart.yaml의 name field가 default)
  nameOverride: "nginx"
  # -- 레플리케이션 Pod 갯수
  replicaCount: 1
  # -- 이미지 정보
  image:
    repository: nginx
    imagePullPolicy: IfNotPresent
    tag: 1.14.2
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    #annotations:
    #  eks.amazonaws.com/role-arn: arn:aws:iam::613674257311:role/service-role/applications3Role-role-app-s3
  # -- 애플리케이션 관련 설정
  application:
    # -- 애플리케이션 포트
    containerPort: 80
    # -- Pod 헬스체크를 위한 LivenessProbe
    #livenessProbe:
    #  httpGet:
    #    path: "/"
    #    port: 9080
    # -- 서비스에 Pod를 추가하기 위한 ReadinessProbe
    #readinessProbe:
    #  httpGet:
    #    path: "/"
    #    port: 9080
        # -- Pod에 환경변수로 넣어줄 추가 정보 - Configmap 에 생성되며 해당 Configmap을 참조
        # configMap:
        #   PROFILE: "SSP-WEB"
        #   COLOR: "#333333"
        #   SKIP_NODE_NAME: "ip-10-202-21-160.ap-northeast-2.compute.internal"
        # envFromfieldRefs:
        #   NODE_NAME: "spec.nodeName"
  
  rollout:
    strategy: "blueGreen"
    trafficRouting: "service"
    #stableWeight: 100
    #previewWeight: 0
    activeService: ""
    previewService: ""
    autoPromotionEnabled: false
    autoPromotionSeconds: {}
    antiAffinity: {}
    maxUnavailable: 0
    prePromotionAnalysis: {}
    postPromotionAnalysis: {}
    scaleDownDelaySeconds: 30
